### ISSUE TITLE
Add bbmod

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-adjust#1]
Would be cool if bbmod were also part of this package. Current implementations can also be improved by replacing the current blur with a true gaussian blur.

**Comment by Setsugennoao** [comment]
Thanks for that function.
You mean this for cropping wrapper?
https://github.com/OpusGang/awsmfunc/blob/master/src/awsmfunc/base.py#L199-L353

**Comment by Setsugennoao** [comment]
Do we still need bbmod

**Comment by Setsugennoao** [comment]
#4
